### PR TITLE
Telepathy deprecation fix to GLibTelepathy (alpha)

### PR DESCRIPTION
**Pull request by srevinsaju**

### CODE REVIEW

**Comment by srevinsaju** [comment]
Telepathy v 0.0.4 is available from PYPI. Install it with `pip3 install telepathy --user`.
Hope it helps :)

**Comment by Aniket21mathur** [comment]
@srevinsaju did you tested collaboration? it might be possible that some constants are different for `telepathy` and `TelepathyGLib`. Doing `from gi.repository import TelepathyGLib as telepathy` might not be sufficient. Please see the guide to [port](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md#how-to-port-an-activity-to-python-3) :-)

**Comment by Aniket21mathur** [comment]
> A mastermind change in the telepathy import to remove deprecation

I wish that your mastermind change works :grin:

**Comment by srevinsaju** [comment]
@Aniket21mathur I know it might run into issues, but it didn't! telepathy hasn't changed much to GLibObject in this case :) . Hopefully it works, I have did all the test I can

**Comment by quozl** [comment]
The most rudimentary interactive testing will show us this change can't work; watch this;

```log
% python
>>> from gi.repository import TelepathyGLib
>>> import telepathy
>>> telepathy.CHANNEL_TYPE_TUBES
'org.freedesktop.Telepathy.Channel.Type.Tubes'
>>> TelepathyGLib.CHANNEL_TYPE_TUBES
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/gi/module.py", line 137, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.TelepathyGLib' object has no attribute 'CHANNEL_TYPE_TUBES'
>>> 
```

You must test before making a pull request.  Don't rely on us to test for you.

**Comment by srevinsaju** [comment]
But @quozl that doesn't work I know too, but the above mentioned commit will work :) in sugar-activity3
The other one is important if we have channels where you have to constantly refactor code and hardwork, but I didn't find any channels here too :+1:

**Comment by srevinsaju** [comment]
Ok, @quozl will try to do as much as I can

**Comment by chimosky** [comment]
@srevinsaju the above commit wouldn't work and @quozl has shown you why. 
Please do try testing your changes before making a PR, as relying on us to test for you isn't great. 
I have to ask this question as I've seen this pattern repeat itself, do you have a development environment setup?

**Comment by chimosky** [comment]
@srevinsaju could you move this to #9.

**Pull request closed without merging**
